OpenUpSA/municipal-data

- municipal_finance/cubes.py
- municipal_finance/settings.py
- municipal_finance/views.py
- requirements.txt
* updated dependencies (old ones didn't work for me)
* refactor cubes into cubes.py
* fix 404 for bad cube names
@jbothma
> Minor tweaks

- models/aged_creditor.json
- models/aged_debtor.json
- models/bsheet.json
- models/capital.json
- municipal_finance/templates/explore.html
- municipal_finance/templates/index.html
- municipal_finance/urls.py
- municipal_finance/views.py
- sql/aged_debtor_labeled.sql
> quickly get an index of all the available cubes out to play with

- models/repmaint.json
- sql/repmaint_labeled.sql
- sql/repmaint_to_labeled.sql
> add repairs and maintenance

- models/aged_creditor.json
- models/aged_debtor.json
- models/bsheet.json
- models/capital.json
- models/incexp.json
- models/repmaint.json
- municipal_finance/templates/docs.html
- municipal_finance/templates/index.html
- municipal_finance/templatetags/lookup.py
- municipal_finance/urls.py
- municipal_finance/views.py
just get something out there that we can put on the event page and start getting feedback on
@longhotsummer
> Initial docs

- municipal_finance/templates/docs.html
- municipal_finance/templates/index.html
> add some query spec

- CHECKS
> CHECKS file

- municipal_finance/settings.py
- municipal_finance/urls.py
> Cache expensive API calls on client and server.

- municipal_finance/static/bower_components/babbage.ui/dist/templates.js
- municipal_finance/static/bower_components/babbage.ui/src/pager.js
- municipal_finance/static/bower_components/babbage.ui/templates/pager.html
Also a fix for upstream: https://github.com/openspending/babbage.ui/pull/37
> FIX babbage-ui paging.

- municipal_finance/profiles.py
- municipal_finance/templates/profile/profile_detail.html
This gets a couple of numbers from the API,
and prints the calculated ratio on the profile page.
@longhotsummer
> Put a basic indicator on the page

- municipal_finance/settings.py
- municipal_finance/templates/embed.html
- municipal_finance/urls.py
- municipal_finance/views.py
by adding some excemptions in the view
> Add forgotten embed.html for babbage and fix xorigin

- models/aged_creditor.json
- models/aged_debtor.json
- models/bsheet.json
- models/capital.json
- models/cflow.json
- models/incexp.json
- models/repmaint.json
- municipal_finance/static/stylesheets/docs.scss
- municipal_finance/templates/docs.html
- municipal_finance/views.py
- sql/labels.sql
looks ok when it's simple
looks bad when it's not simple
and we need to figure out what's up with the cash flow data - why we have codes that they haven't defined anywhere
> Add item docs

- models/aged_creditor.json
- models/aged_debtor.json
- models/bsheet.json
- models/capital.json
- models/cflow.json
- models/incexp.json
- models/repmaint.json
- municipal_finance/static/stylesheets/docs.scss
- municipal_finance/templates/docs.html
- municipal_finance/views.py
- sql/labels.sql
Reverts Code4SA/municipal-data#28
> Revert "Revert "Add item docs""

- Procfile
Reverts Code4SA/municipal-data#29
> Revert "add item docs again with extended timeout"

- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
> Operating budget

- municipal_finance/static/slate/stylesheets/screen.css
- municipal_finance/static/slate/stylesheets/screen.css.scss
- municipal_finance/static/stylesheets/docs.scss
- municipal_finance/templates/docs.html
@jbothma 
This is intended to replace #36
> Wider docs, tweaks to tables

- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
I had to change the way the URL was constructed to get budgeted amounts.
@jbothma
> Initial capital budget

- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
> Repairs and maintenance

- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
> Use audited numbers

- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
> Mayoral staff outline

- requirements.txt
- scorecard/static/js/profile_map_mapit.js
We're loading metros and local munis.
> Load geometry from mapit and ensure shapes are clickable

- municipal_finance/middleware.py
- municipal_finance/utils.py
> Pass through error status code to json response

- municipal_finance/static/javascript/table.js
We don't persist these highlighted items.
Merge this before #59.
> Highlight items with particular codes mentioned in the query string

- municipal_finance/wsgi.py
- requirements.txt
> Use psycogreen to make psycopg2 async-io friendly with gevents.

- formats/en_ZA/formats.py
- municipal_finance/settings.py
- scorecard/templates/profile/profile_detail.html
@xybrnet this relates to your charts change, merge if you're happy
> Use en-za formatting (spaces for thousands separator)

- scorecard/templates/profile/profile_detail.html
> Audit outcomes in performance section

- municipal_finance/cubes.py
This reads each cube model from disk and introspects the DB table only once
per python process
> Use CachingJSONCubeManager

- municipal_finance/__init__.py
- municipal_finance/cubes.py
- municipal_finance/settings.py
- municipal_finance/views.py
- scorecard/profile_data.py
https://github.com/ross/requests-futures
> Scorecard parallel api requests

- scorecard/profile_data.py
based on top of https://github.com/Code4SA/municipal-data/pull/123/files
> Query code not label

- municipal_finance/data_import/create_indices.py
- municipal_finance/views.py
- sql/create_indices.sql
- sql/table_badexp_facts.sql
> Add badexp cube and make index creation order stable

- municipal_finance/settings.py
but currently no risk of CSRF so safe for everything
https://docs.djangoproject.com/en/1.9/ref/middleware/#module-django.middleware.gzip
> Add gzip middleware mainly for CSV downloads

- municipal_finance/context_processors.py
- municipal_finance/settings.py
- municipal_finance/static/javascript/table.js
- municipal_finance/static/stylesheets/table.scss
- municipal_finance/templates/table.html
- scorecard/profile_data.py
- scorecard/templates/profile/profile_detail.html
- scorecard/templatetags/finance.py
* amount types are choosable
* make it work with more tables (Still breaks on some tables that don't have financial_period)
* remove scale
* download is a button in the top right, disable rather than hiding when it doesn't work
> Table view updates

- municipal_finance/templates/docs.html
Let the nerds who love reading every bit of docs and not dive in scroll a bit
https://www.pivotaltracker.com/story/show/120584245
> Move the dataset-specific docs front and center.

- municipal_finance/static/stylesheets/scorecard.scss
- scorecard/templates/profile/profile_detail.html
Move audit opinions descriptions onto own row
Reduce text copy
Some style adjustments
> Reformat audit opinion descriptions

- municipal_finance/static/stylesheets/scorecard.scss
- scorecard/profile_data.py
- scorecard/profiles.py
- scorecard/static/js/charts.js
- scorecard/templates/profile/profile_detail.html
Also:
* draw charts based on data attributes to simplify things
* the data is injected automatically via the profileData var in javascript.
> Indicators for staff and contractor expenses

- scorecard/profile_data.py
- scorecard/templates/profile/profile_detail.html
Add corporate services to GAPD
> Updates to GAPD 

- municipal_finance/static/stylesheets/scorecard.scss
- scorecard/static/js/charts.js
- scorecard/templates/profile/profile_detail.html
> Explanations for income and expenditure

- scorecard/templates/_base.html
- scorecard/templates/about.html
- scorecard/templates/homepage.html
> Link about page into rest of site

- municipal_finance/static/stylesheets/table.scss
- municipal_finance/templates/table.html
Tweaks to table view to make more room for documentation link
> Table tweaks

- scorecard/static/js/charts.js
- scorecard/templates/profile/profile_detail.html
- scorecard/templatetags/finance.py
Suggestion from Adi, which is nice for numbers like 0.8 months.
> Months to days

- municipal_finance/static/javascript/table.js
- municipal_finance/static/stylesheets/table.scss
- municipal_finance/templates/table.html
This makes it easier to say add all metros, all locals, all districts.
> User can choose munis based on category

- municipal_finance/static/javascript/table.js
- municipal_finance/static/stylesheets/site.scss
- municipal_finance/templates/index.html
- municipal_finance/templates/layout.html
* quick link to add all munis in table view
* 39 million facts on api landing page
* link to muni money on landing page
> Link to all munis, more info on API landing page

- scorecard/static/js/scorecard.js
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/_videos.html
- scorecard/templates/homepage.html
- scorecard/templates/profile/profile_detail.html
Allow user to choose languages on homepage
Show Sesotho
> Improvements to video chooser

- models/capital.json
- scorecard/profile_data.py
- scorecard/templates/profile/profile_detail.html
* Also typo correction on "Capital Acquisition"
> Repmaint from capital acqusition

- scorecard/profile_data.py
- scorecard/profiles.py
- scorecard/templates/profile/profile_detail.html
- governenment vs locally generated revenue comparison
- more detailed revenue breakdown
The breakdown percentages look different from the old ones so I need to check that but here's the structure so long
> Income story

- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/homepage.html
* move map lower down page so that video is near the top
* call to action on the map
This has been requested by treasury.
> Adjust homepage map

- municipal_finance/static/javascript/table.js
- municipal_finance/templates/table.html
- municipal_finance/utils.py
- municipal_finance/views.py
- requirements.txt
* xlsx
* for both xlsx and csv, include all dimension attributes except the function (we'll deal with that later)
* ensure downloads are ordered by municipality and then item position (or item code)
> XLSX downloads

- municipal_finance/middleware.py
- municipal_finance/settings.py
> Quick hack for http basic auth

- municipal_finance/static/javascript/table.js
- municipal_finance/static/stylesheets/table.scss
- municipal_finance/templates/table.html
- == null
0 == 0
I'm not sure if this will be clear. Thoughts?
> Make zero vs null clearer in table view

- municipal_finance/static/javascript/table.js
- municipal_finance/templates/table.html
* also ensure you keep the chosen munis when the dataset is changed
* downloads include functions if we're filtering by them
> Group table view by function

- scorecard/static/js/scorecard.js
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/profile/_about.html
* email the first two secretaries that we have
* cc us
* include a link to the page
> Send email button

- municipal_finance/settings.py
- municipal_finance/static/javascript/app.js
- municipal_finance/static/stylesheets/site.scss
- municipal_finance/templates/index.html
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/_base.html
* video in API
* email links
* logos
* improved footers
> Final tweaks

- scorecard/templates/locate.html
- scorecard/urls.py
- scorecard/views.py
Not sure when this stopped working :(
> Fix location finding

- municipal_finance/static/javascript/table.js
> Update download link before rendering

- scorecard/profile_data.py
- scorecard/profiles.py
- scorecard/templates/profile/_performance.html
Seems to work alright. This is of course super clearly defined... By which I mean I don't know what to cite yet.
I can't match this well to everything yet but Kouga and NMA seemed to match fairly well
> Liquidity ratio

- README.md
- sql/upsert/aged_creditor.sql
- sql/upsert/aged_debtor.sql
- sql/upsert/bsheet.sql
- sql/upsert/capital.sql
- sql/upsert/cflow.sql
- sql/upsert/conditional_grants.sql
- sql/upsert/incexp.sql
- sql/upsert/repmaint.sql
I think it's alright to do this with SQL right now but a nice next step would be to manage the DB schema with alembic and then it should be pretty easy to to the import with python code which would remove the need for dropping NOT NULL constraints in the transaction.
> SQL code to update the database with the 2016q4 published section 71 data.

- scorecard/templates/profile/_about.html
> Show 'not yet available' for mayor and deputy and link for mobile

- municipal_finance/templates/layout.html
This might allow us to encourage browsers to find out about municipaldata.treasury.gov.za
> Prove ownership to Google and Bing

- scorecard/templates/sitemap.txt
- scorecard/urls.py
- scorecard/views.py
I know this isn't critical, but I wanted to do some coding and it's all my brain can handle right now. :)
> Sitemap.txt

- scorecard/profiles.py
> Exclude comparatives for which there are no other munis to compare with

- scorecard/static/js/scorecard.js
- scorecard/static/stylesheets/print.css
- scorecard/static/stylesheets/print.scss
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/profile/_about.html
- scorecard/templates/profile/_demarcation_notice.html
- scorecard/templates/profile/profile_detail.html
- scorecard/templatetags/dates.py
- scorecard/views.py
Notice on page for disestablished munis.
> Disestablished notice

- scorecard/profile_data.py
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/profile/_demarcation_indicator_notice.html
- scorecard/templates/profile/_demarcation_notice.html
- scorecard/templates/profile/_income.html
- scorecard/templates/profile/_performance.html
- scorecard/templates/profile/_spending.html
- scorecard/templatetags/finance.py
- scorecard/views.py
Notices for newly established munis that are missing indicators.
> Established notice

- scorecard/profiles.py
- scorecard/static/js/charts.js
- scorecard/static/stylesheets/scorecard.scss
- scorecard/templates/faq.html
- scorecard/templates/profile/_comparative_list.html
* still waiting on Ayesha's feedback on the FAQ entry
> Expand on what 'similar municipalities' means

- municipal_finance/static/javascript/table.js
Haven't tried this before ,let's see how it goes.
> JS Exception tracking with Google Analytics

- scorecard/profile_data.py
so that it doesn't give different results just before/after new year
> Hardcode in-year years

- README.md
When I first setup the project  ```pip install -r requirements.txt``` gave a whole bunch of build errors.
I thought I document this with the appropriate solutions
> More detailed instructions for local development

- scorecard/models.py
attribute itervalues() changes to values() in python3
> python2 -> python3 change

- README.md
- docker-compose.portal-gunicorn.yml
- docker-compose.portal.yml
- municipal_finance/cubes.py
Move SQLAlchemy engine initialisation into method - it was hapening
before django initialisation when it was a module property
> Set up docker-compose and docs to update materialised views using docker

- scorecard/templates/profile/_resources.html
Fix for the issue: https://trello.com/c/VtU3AvKs/152-resources-links-do-not-work
> Fixed broken resource links and some copy (152)

- municipal_finance/tests/test_analytics.py
Small change related to https://trello.com/c/EiaJsovr/467-exclude-staging-site-from-search-engines
> Improved testing of no_index flag

- assets/js/components/audit-opinions.js
- demo-data.json
- scorecard/compile_profiles.py
- scorecard/profile_data/api_data.py
Issue: https://trello.com/c/puyizh9F/519-audit-report-years-config-why-is-audit-report-2015-16-blank-for-buf-on-staging-are-we-doing-the-wrong-thing-with-mapping-years-t
> Show 'no report available' message if opinion report URL is null

- requirements.txt
- yarn.lock
Issue: https://trello.com/c/EDsM5OPx/542-identify-any-upgrade-recommendations-we-need-to-tackle-urgently-tb-1-day
> Dependency updates

- bin/start-web.sh
Issue: https://trello.com/c/kjOl2RDC/574-selecting-all-munis-at-once-breaks-data-explorer
> Increase Gunicorn request size limit

- infrastructure/static/js/mm-webflow.js
Issue: https://trello.com/c/uI4wLyXe/540-remove-unplanned-search-box-muni-dropdown-on-capital-project-search-page-tb-05d
> Hide dropdown search on infra muni dropdown

- assets/js/components/indicators.js
- infrastructure/package.json
- package.json
Issue: https://trello.com/c/7g64hItz/579-user-query-some-funny-figures-for-2019-2020-and-2018-2019-shown-for-ethekwini-in-the-repairs-and-maintenance-scorecard
> Update municipal-money-charts module

- municipal_finance/templates/index.html
- municipal_finance/templates/table.html
Issue: https://trello.com/c/ajRLXx7C/573-stop-offering-unsupported-cubes-in-the-data-explorer-est-1-day
> Don't link to cubes without items

- models/aged_creditor.json
- models/aged_creditor_v2.json
- models/aged_debtor.json
- models/aged_debtor_v2.json
- models/audit_opinions.json
- models/bsheet.json
- models/capital.json
- models/capital_v2.json
- models/cflow.json
- models/cflow_v2.json
- models/conditional_grants.json
- models/financial_position_v2.json
- models/grants_v2.json
- models/incexp.json
- models/incexp_v2.json
- models/repmaint.json
- models/repmaint_v2.json
- models/uifwexp.json
- municipal_finance/templates/docs.html
Issue: https://trello.com/c/F6Z7RmLy/571-valid-queries-as-a-user-i-would-like-to-know-how-to-perform-valid-queries-against-the-api-so-that-i-dont-end-up-with-nonsensical
> Add documentation for non-aggregatable dimensions

- assets/js/components/income.js
- scorecard/tests/test_scorecard.py
Issue: https://trello.com/c/jTW2HsGs/547-qnull-instead-q1-or-q3-or-whatever-tb1-1-day-tb2-3-days
> Make the legend dispaly year/quarter for grants indicators

- scorecard/profile_data/indicators/__init__.py
Issue: https://trello.com/c/G5tEOpsa/558-local-income-sources-dont-add-up-to-total
> Handle null revenue types

- infrastructure/static/css/muni-money-infra.webflow.css
- infrastructure/static/css/webflow.css
- infrastructure/static/js/webflow.js
- infrastructure/static/js/webflow/import-project.js
- infrastructure/templates/infrastructure/list.html
- infrastructure/templates/infrastructure/project.djhtml
- infrastructure/templates/infrastructure/search.djhtml
Issue: https://trello.com/c/Pssa8p7m/541-tooltips-are-shown-under-map-on-detail-page
> Webflow import - show tooltip above map

- infrastructure/static/js/mm-webflow.js
- infrastructure/tests/test_search_page.py
Issue: https://trello.com/c/whChCWej/551-changes-to-capital-project-search-fields-should-apply-on-change-enter-key
> Trigger search on pressing enter or changing dropdowns

- assets/js/municipal-money.js
- scorecard/tests/test_search.py
Issue: https://trello.com/c/doxEoNws/562-fix-search-form-enter-keypress-event-triggering-webflow-form-appearing-broken-est-1-day
> Prevent default enter key behaviour for search inputs

- household/upload.py
Issue: https://trello.com/c/nWZSgAbB/555-can-admins-update-household-bills-via-admin-ui-tb-1-day
> Household bills fixes

- app.json
- heroku.yml
- requirements.txt
Issue: https://trello.com/c/PmaUmkXQ/611-review-apps-in-heroku
> Set up review app using Heroku

- webflow/static/webflow/css/components.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Issue: https://trello.com/c/uXj7U0WI/550-capital-project-link-as-a-user-i-would-like-to-discover-that-capital-projects-exist-so-that-i-can-learn-about-what-municipalitie
> Capital project link

- demo-data.json
Issue: https://trello.com/c/JeXdYWHd/622-add-superuser-to-demodata-as-in-wazimap-ng
> Add superuser to demo data

- household/static/household/js/household.js
Issue: https://trello.com/c/almeayLB/624-household-bills-years-are-shown-out-of-order
> Set x axis ordering for Plotfy

- assets/js/components/audit-opinions.js
- assets/js/components/contacts.js
- assets/js/components/indicators.js
- assets/js/pages/profile.js
- municipal_finance/static/javascript/app.js
Issue: https://trello.com/c/op92KSWU/625-additional-custom-event-tracking-using-google-analytics
> Feature 625 additional custom event tracking

- assets/js/pages/help.js
Issue: https://trello.com/c/npkAFhXR/640-ensure-all-small-size-videos-are-actually-below-15mb-unless-that-makes-them-too-low-quality-to-read-the-text
> Change help video file sizes

- packages.txt
- requirements-test.txt
- requirements.txt
Issue: https://trello.com/c/khV4zc9K/642-ci-is-broken-probably-due-to-a-dependency-issue
> Remove unused codecov

- webflow/static/webflow/css/components.css
- webflow/static/webflow/css/municipalmoney.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Issue: https://trello.com/c/NL6u2rmR/648-video-section-is-confusing-on-mobile
> Video section mobile compatibility

- README.md
- demo-data.json
- infrastructure/tests/test_scorecard_indicator.py
- scorecard/fixtures/scorecard-no-data.json
- scorecard/profiles.py
Issue: https://trello.com/c/PTRIIlKv/651-mscoa-data-in-demo-data
> MSCOA demo data

- assets/js/components/spending.js
- assets/js/pages/profile.js
- assets/scss/municipal-money.scss
- package.json
- scorecard/profile_data/api_data.py
- scorecard/profile_data/indicators/__init__.py
- scorecard/profiles.py
- yarn.lock
Issue: https://trello.com/c/rMyDmG2P/372-this-chart-is-not-consistent-with-the-style-of-the-current-mm-and-very-busy-challenging-to-understand
The chart library must be updated first before merging these changes
> Make spending breakdown chart consistent with other charts

- scorecard/profile_data/indicators/__init__.py
Follow up change to https://github.com/OpenUpSA/municipal-data/pull/685
> Use V2 data for expenditure functional breakdown

- assets/js/pages/profile.js
- scorecard/profile_data/indicators/__init__.py
Reverting the chart implementation of https://github.com/OpenUpSA/municipal-data/pull/685
> Revert spending chart

- municipal_finance/static/javascript/app.js
- municipal_finance/templates/index.html
- municipal_finance/tests/test_portal_landing_page.py
Issue: https://trello.com/c/lUamHOOK/694-when-you-click-on-municipality-dropdown-some-weird-stuff-happens
> Bug 694 clicking data explorer dropdowns breaks UI

- municipal_finance/admin.py
Issue: https://trello.com/c/XFutGejg/646-missing-code-feedback-as-an-admin-i-would-like-better-guidance-to-update-dimension-codes-and-labels-so-that-i-can-upload-updates
> NoneType fix

- .github/workflows/test.yml
- README.md
- app.json
- assets/js/components/formula.js
- household/static/household/js/household.js
- household/tests/test_charts.py
- webflow/static/webflow/css/municipalmoney.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Story: https://trello.com/c/FV6Zj1HP/701-household-bills-update-the-information-sections-05
> Household bills info sections and chart improvements

- scorecard/profile_data/indicators/__init__.py
Issue: https://trello.com/c/NTIKBVfx/706-support-v2-data-in-summary-of-spend-by-functional-classification
> Support v2 data in summary of spend by functional classification

- app.json
- docker-compose.yml
- municipal_finance/settings.py
> Renamed ENVIRONMENT envvar to SENTRY_ENVIRONMENT 

- scorecard/profile_data/api_data.py
Issue:https://trello.com/c/NTIKBVfx/706-support-v2-data-in-summary-of-spend-by-functional-classification
> Feature 706 improve consistent charts

- scorecard/profile_data/indicators/__init__.py
Issue: https://trello.com/c/NTIKBVfx/706-support-v2-data-in-summary-of-spend-by-functional-classification
> Functional breakdown chart - adjust V1/V2 years

- municipal_finance/admin.py
- municipal_finance/bulk_download.py
- municipal_finance/settings.py
- municipal_finance/summarise_data.py
- municipal_finance/update/aged_debtor_facts_v2.py
Issue: https://trello.com/c/MbTlEBqv/673-bulk-download-as-a-user-i-would-like-to-be-able-to-download-any-and-all-the-in-the-system-so-that-i-can-use-it-for-my-own-analys
> Feature 673 bulk downloads

- municipal_finance/templates/docs.html
- municipal_finance/views.py
Issue: https://trello.com/c/MbTlEBqv/673-bulk-download-as-a-user-i-would-like-to-be-able-to-download-any-and-all-the-in-the-system-so-that-i-can-use-it-for-my-own-analys
> Tweak URL used in bulk download docs

- municipal_finance/settings.py
- scorecard/profile_data/api_data.py
- scorecard/profile_data/indicators/__init__.py
Issue: https://trello.com/c/7VWaQtCd/726-overlapping-on-the-bar-graph
> Overlapping on the functional breakdown graph

- webflow/static/webflow/css/components.css
- webflow/static/webflow/css/municipalmoney.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Issue: https://trello.com/c/tet9LbQo/725-feature-i-feedbackmunicipalmoneygovza
> Email feedback modal

- webflow/static/webflow/css/municipalmoney.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Story: https://trello.com/c/LyyrBvSn/702-household-bills-user-test-new-wording-feature-of-catergory-examples-do-users-understand-the-wording-and-flow-or-do-they-get-stuc
Webflow staging: https://municipalmoney.webflow.io/muni-profile
Webflow export: https://app.gitbook.com/o/-Ly4_0FbvQFY-m3TOzuc/s/-M7h3WmFP96pTHYzQ_vd/development-and-devops/exports-and-changelog/january-2024
> Household Bills UX improvements

- README.md
- assets/js/components/comparison-menu.js
Story: https://trello.com/c/DnLNCgev/755-chart-comparison-municipality-list-is-not-removed-when-selecting-no-comparison
> Hide key when selecting no comparison

- webflow/static/webflow/css/components.css
- webflow/static/webflow/js/municipalmoney.js
- webflow/templates/webflow/help.html
- webflow/templates/webflow/index.html
- webflow/templates/webflow/locate.html
- webflow/templates/webflow/muni-profile.html
- webflow/templates/webflow/terms.html
Story: https://trello.com/c/X4zq99ur/760-household-bills-i-last-updated-in-2009
> Remove household bills last updated notice

- municipal_finance/templates/docs.html
- municipal_finance/templatetags/format_cube_name.py
- municipal_finance/views.py
Story: https://trello.com/c/WwiZWRof/730-as-a-user-i-would-like-the-bulk-downloads-to-be-ordered-in-a-more-consistent-way
> Order bulk downloads alphabetically

- municipal_finance/static/stylesheets/table.scss
Story: https://trello.com/c/zGPU5GwX/688-data-explorer-ux-alternating-colours-for-rows-small
> Alternate table row colors

- municipal_finance/static/javascript/table.js
- municipal_finance/static/stylesheets/table.scss
- municipal_finance/templates/table.html
- municipal_finance/views.py
Story: https://trello.com/c/EovGibqk/678-s-data-explorer-ux-improve-visual-priority-spacing-standard-ux-heuristic-stuff-small
> Data explorer UX improvements

- docker-compose.yml
- municipal_finance/templates/maintenance.html
- municipal_finance/templates/table-maintenance.html
- municipal_finance/views.py
Story: https://trello.com/c/qwgGG2SK/786-item-code-updates-historical-data
> Add maintenance notice to data explorer

- municipal_finance/bulk_download.py
Story: https://trello.com/c/qwgGG2SK/786-item-code-updates-historical-data
> Disable xlsx bulk dumps for these datasets

- municipal_finance/bulk_download.py
- municipal_finance/tests/test_bulk_download.py
Story: https://trello.com/c/NWMJNbO5/789-bulk-download-data-summary-causing-server-freeze
> Improve performance when writing to bulk download files

- municipal_finance/fixtures/initial/amount_type_v2.csv
- municipal_finance/update/utils.py
Story: https://trello.com/c/HBgfNM8t/796-nt-uploads-failing
> Handling RAUD amount types

- municipal_finance/update/capital_facts_v2.py
- municipal_finance/update/cash_flow_v2.py
- municipal_finance/update/financial_position_facts_v2.py
- municipal_finance/update/income_expenditure_v2.py
Use all codes, not only those from the latest schema version
Story https://trello.com/c/X2qdda3X/797-q4-upload-bug
> Use all current item codes
