OpenUpSA/municipal-data

sql/aged_creditor_labeled.sql, sql/aged_debtor_labeled.sql, sql/bsheet_labeled.sql, sql/capital_labeled.sql, sql/cflow_labeled.sql, sql/incexp_labeled.sql, sql/repmaint_labeled.sql
This is fine because sorting works fine on integers and deals with the
ambiguity of of the API and type casting in cuts
@longhotsummer
=> Change financial_period to integer

scorecard/templates/404.html, scorecard/templates/500.html
I was doing these for umibukela so copied them here quickly.
The 404 page pushes a Google Analytics event so that we can track them and their referrer.
=> 404 and 500 error pages

models/aged_creditor.json, models/aged_debtor.json, models/audit_opinions.json, models/badexp.json, models/bsheet.json, models/capital.json, models/cflow.json, models/conditional_grants.json, models/incexp.json, models/municipalities.json, models/officials.json, models/repmaint.json, scorecard/profile_data.py, scorecard/profiles.py, scorecard/templates/profile/profile_detail.html
One option is to have this in the model as done here. I don't think this justifies a cube. On the other hand this is a (cheap) query per cube.
The idea with last_updated is to be a partial ISO8061 time where the rest can be parsed as zeros - perhaps it's worth just having the full timestamp but that's kinda saying more than we can?
This is the precursor to being able to indicate somewhere "The contact details are correct as at xxxx and is updated quarterly"
The update_cycle values can match values in "period_length" which are currently year and month although "quarterly" and "annual" are really the terms used for this kind of thing
=> WIP Indicate when the contact details were last updated

scorecard/profile_data.py, scorecard/templates/profile/profile_detail.html
* reverse direction: calculate `actual - budget` so that underspending is < 0 and overspending is > 0.
* explain over and under
* ensure chart uses non-absolute value
=> Correct cap and opex spend sign and make clearer

scorecard/profiles.py, scorecard/templates/profile/profile_detail.html, scorecard/templatetags/finance.py, scorecard/urls.py, scorecard/views.py
This makes it much more understandable.
No need for Wazimap's weird "geography.this" stuff. We get to use the actual geography object in the template, not a python dict version.
=> Replace Wazimap's GeographyDetailView with our own

scorecard/static/js/place-finder.js
Now we correctly take google results and look them up as munis. We still should go to mapit directly, but that'll be another change.
=> Fix geocoding place search

models/badexp.json, municipal_finance/settings.py, municipal_finance/static/javascript/table.js, municipal_finance/static/javascript/vendor/js.cookie.js, municipal_finance/static/stylesheets/site.scss, municipal_finance/static/stylesheets/table.scss, municipal_finance/templates/index.html, municipal_finance/templates/table.html, municipal_finance/views.py
* add direct links to the dataset table view from the landing page
* the table view saves a cookie for the Terms of Use and prompts the user to accept
=> Make the focus of API websites the data, not the docs

Procfile
See
http://docs.gunicorn.org/en/latest/settings.html?highlight=limit_request_line
This prevents errors when specifying all municipalities by code
=> Up gunicorn request limit to 7k

municipal_finance/middleware.py
This means the website is hidden, but the API still works
=> Auth for non-api urls for muni finance

scorecard/static/js/maps.js
This prevents us from getting the 2016 municipal boundaries.
=> Specify generation=1 for mapit calls

scorecard/templates/profile/_about.html, scorecard/templates/profile/_income.html, scorecard/templates/profile/_performance.html
* Under the contact details banner, change “Mayoral staff” to “Mayoral positions"
* Change 'Current Debtors’ Collection Rate' heading to read  ‘Current Debtors’ Collection Ratio’ so that it aligns with the headings we are using on the video clips. 
* “Income” we recently asked you to add the name of the municipality in the heading “ x municipality gets money from two sources”.  Please can we change that to “Where does x municipality get its money from?”  
* The link to the Liquidity video clip is also to be added to the Current Ratio indicator.  We covered both indicators in one clip.
=> Final tweaks

scorecard/profile_data.py
"municipalities to use the GFS function Budget and Treasury Office
to report on Property rates so that we can deduct Revenue Forgone
from the correct function.  Revenue forgone is only applicable to
Property rates, Water, Electricity, Sanitation (Waste water) and
Waste Management. If you look at table SA1 in the MBRR A1 Schedule
– you will see how we calculate"
=> Subtract Revenue Foregone from Property Rates and Services

scorecard/static/stylesheets/scorecard.scss, scorecard/templates/profile/_performance.html, scorecard/templates/profile/_spending.html
I don't think it's clear where to find the explanation of the asterisk - especially since it's not clear it's hyperlinked.
But the underline on the subscript doesn't look good
The text looks kinda useful, but without underline it looks more like a heading for the description below
I think with underline (always, not just on hover) it works - even though it makes the indicator busier.
=> Link from "Not available" in scorecard to FAQ entry

scorecard/templates/profile/_about.html
Don't show mayor or deputy mayor since those positions are out of date since the local elections. Keep the places to indicate that this information exists and will come soon.
Explain a) that it's updated quarterly and b) that they're hidden because of the recent elections.
I think mentioning "political appointments" works a little toward educating that mayor and deputy are appointed differently from managers.
=> Hide out of date political appointments and explain

municipal_finance/cubes.py, municipal_finance/middleware.py, municipal_finance/settings.py, scorecard/profile_data.py
This means long queries will fail instead of queuing and building up to
hours of downtime.
Also start handling the error nicely. Currently we just get internal feedback
of "APIOverloadedException" but I'd like to turn that into a "We're oh so popular"
message when I figure out how to use 'process_exception' correctly
=> Set DB statement timeout to 10s to reduce impact of overload

scorecard/static/stylesheets/scorecard.scss
Adjustments to positioning and size to make the page easier to read. Gathered while working on mockups for comparisons.
* smaller plus alongside 'show calculation'
* move chart down a bit so that indicator value stands out
* smaller key (key and 'did you know' text is now the same size), so that key is secondary and not primary
* key shifted left slightly so that text aligns (less visual noise from different vertical lines)
* less **heavy bold** text
Before:
After
=> Profile page tweaks

scorecard/static/js/maps.js, scorecard/templates/profile/profile_detail.html
For disestablished munis, we show the old boundary in yellow (to match the colour of the warning banner), and then load the 2016 boundaries on top of that.
when hovering:
=> Use generation 2 maps in general, 1 for old munis

municipal_finance/utils.py
Downloading of excel files failed due to they way the zip module in python3 writes files, zip module writes as bytes not strings
=> Download Excel Files

requirements.txt
I regenerated materialised views against the portal with the new sqlalchemy version and didn't get any diffs, suggesting it's working as expected.
=> Upgrade SQLAlchemy

assets/js/components/indicators.js, scorecard/views.py
Remove default limit for this geography endpoint by setting paginator to None and update the api call response in indicator.js
=> Bugfix: Remove default limit for this geography endpoint

scorecard/profile_data/api_data.py, scorecard/profile_data/indicators/capital_budget_spending.py, scorecard/profile_data/indicators/utils.py, scorecard/tests/indicators/__init__.py, scorecard/tests/indicators/test_capital_budget_spending.py, scorecard/tests/indicators/test_uifw_expenditure.py
- filter v2 capital expenditure query to only new, upgrading and renewal
- don't mix v1 and v2 data for capital expenditure calculation - other indicators still need this fix
=> Fix capital expenditure calculation on v2 cube data

assets/js/components/audit-opinions.js
Issue: https://trello.com/c/zkpTAAWK/316-audit-report-links-dont-open-the-pdf-in-chrome
=> Remove PDF files from URLs serving with http only

municipal_finance/static/javascript/table.js
Issue: https://trello.com/c/nBtl0CWe/515-dont-show-capex-v2-table-to-users-while-its-aggregating-stuff-it-shouldnt
=> Add notice to capex v2 page on the data explorer

assets/js/components/indicators.js
Related issue: https://trello.com/c/dJaVjMse/514-upload-latest-financial-performance-data-update
=> Hide formula elements only for an indicators corresponding latest_year

municipal_finance/fixtures/tests/update/audit_opinion_facts/insert.csv, municipal_finance/fixtures/tests/update/audit_opinion_facts/update.csv, municipal_finance/tests/update/test_audit_opinion_facts.py, municipal_finance/update/audit_opinion_facts.py
Issue: https://trello.com/c/MdwRsxXZ/517-add-support-for-audit-report-url-to-audit-opinion-facts-update-est-1-day
=> Add report_url to audit opinion facts

assets/js/components/audit-opinions.js
Issue: https://trello.com/c/t7OBk8r4/545-verify-treasurys-audit-opinion-report-files
=> Use falsy to check that audit report URL is not available

municipal_finance/static/stylesheets/docs.scss, municipal_finance/static/stylesheets/site.scss, municipal_finance/static/stylesheets/table.scss, municipal_finance/templates/docs.html, municipal_finance/templates/layout.html, municipal_finance/templates/layout_data.html, municipal_finance/templates/table.html
Issue: https://trello.com/c/cOcFTbQS/525-show-site-notices-on-data-explorer-site-incl-docs-so-that-users-who-somehow-land-there-know-that-it-isnt-official-data-est-1d
=> Add site notices to data explorer

infrastructure/package.json, package.json, scorecard/profile_data/indicators/grants.py
Issue: https://trello.com/c/Y7Ji21GR/358-grey-bar-for-grant-amount-spent-is-hidden-below-the-main-chart-row-est-05
=> Update muni chart package version

infra-demo-data.json
Issue: https://trello.com/c/s7gs3N9n/636-add-demo-dev-data-for-capital-projects-which-loads-in-heroku-automatically
=> Add more financial years to infra demo data

household/chart.py, household/static/household/js/household.js, household/tests/test_charts.py
Issue: https://trello.com/c/x8pUvaMG/615-why-is-2015-16-and-2016-17-not-shown-in-this-household-bills-service-update
=> Include years from service data on service breakdown charts

municipal_finance/views.py
Issue: https://trello.com/c/qhVEIWhC/719-django-worker-intermittent-error-when-reading-from-s3
=> Set bulk download storage URL

assets/js/pages/profile.js
Story: https://trello.com/c/5aErVWq0/731-household-bills-charts-are-not-showing-on-the-scorecard-after-the-2023-q4-update
=> Render household bill charts using partial data
